### PR TITLE
Fix out of bounds problem

### LINKED ISSUE #285: Fix ground segmentation memory leaks
1.
```
==10808== 50,304 bytes in 588 blocks are indirectly lost in loss record 95 of 101
==10808==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10808==    by 0x134FA357: __gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*) (new_allocator.h:104)
==10808==    by 0x134F30DC: std::allocator_traits<std::allocator<int> >::allocate(std::allocator<int>&, unsigned long) (alloc_traits.h:491)
==10808==    by 0x134EBF73: std::_Vector_base<int, std::allocator<int> >::_M_allocate(unsigned long) (stl_vector.h:170)
==10808==    by 0x134EC331: void std::vector<int, std::allocator<int> >::_M_emplace_back_aux<int>(int&&) (vector.tcc:412)
==10808==    by 0x134E4AC4: void std::vector<int, std::allocator<int> >::emplace_back<int>(int&&) (vector.tcc:101)
==10808==    by 0x134D8C9D: std::vector<int, std::allocator<int> >::push_back(int&&) (stl_vector.h:932)
==10808==    by 0x1352214D: wave::GroundSegmentation<pcl::PointXYZI>::genPolarBinGrid() (ground_segmentation.hpp:65)
==10808==    by 0x13520835: wave::GroundSegmentation<pcl::PointXYZI>::applyFilter(pcl::PointCloud<pcl::PointXYZI>&) (ground_segmentation.hpp:364)
==10808==    by 0x134E1B2B: pcl::Filter<pcl::PointXYZI>::filter(pcl::PointCloud<pcl::PointXYZI>&) (filter.h:151)
==10808==    by 0x134C6FCF: occupancy::OccupancyNodelet::segmentGround() (occupancy_nodelet.cpp:540)
==10808==    by 0x134C48DB: occupancy::OccupancyNodelet::lidarCallBack(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) (occupancy_nodelet.cpp:270)
```
2.
```
==10808== 57,600 bytes in 40 blocks are indirectly lost in loss record 96 of 101
==10808==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10808==    by 0x13509A32: __gnu_cxx::new_allocator<wave::SignalPoint>::allocate(unsigned long, void const*) (new_allocator.h:104)
==10808==    by 0x13504DD3: std::allocator_traits<std::allocator<wave::SignalPoint> >::allocate(std::allocator<wave::SignalPoint>&, unsigned long) (alloc_traits.h:491)
==10808==    by 0x134FF78F: std::_Vector_base<wave::SignalPoint, std::allocator<wave::SignalPoint> >::_M_allocate(unsigned long) (stl_vector.h:170)
==10808==    by 0x134F8D24: std::vector<wave::SignalPoint, std::allocator<wave::SignalPoint> >::_M_default_append(unsigned long) (vector.tcc:557)
==10808==    by 0x134F1B42: std::vector<wave::SignalPoint, std::allocator<wave::SignalPoint> >::resize(unsigned long) (stl_vector.h:676)
==10808==    by 0x134E9FB4: wave::GroundSegmentation<pcl::PointXYZI>::initializePolarBinGrid() (ground_segmentation.hpp:25)
==10808==    by 0x13521F1C: wave::GroundSegmentation<pcl::PointXYZI>::genPolarBinGrid() (ground_segmentation.hpp:38)
==10808==    by 0x13520835: wave::GroundSegmentation<pcl::PointXYZI>::applyFilter(pcl::PointCloud<pcl::PointXYZI>&) (ground_segmentation.hpp:364)
==10808==    by 0x134E1B2B: pcl::Filter<pcl::PointXYZI>::filter(pcl::PointCloud<pcl::PointXYZI>&) (filter.h:151)
==10808==    by 0x134C6FCF: occupancy::OccupancyNodelet::segmentGround() (occupancy_nodelet.cpp:540)
==10808==    by 0x134C48DB: occupancy::OccupancyNodelet::lidarCallBack(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) (occupancy_nodelet.cpp:270)
```
3.
```
==10808== 21,924 bytes in 176 blocks are indirectly lost in loss record 94 of 101
==10808==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10808==    by 0x51F272D: void std::vector<int, std::allocator<int> >::_M_emplace_back_aux<int const&>(int const&) (in /opt/ros/kinetic/lib/libroscpp.so)
==10808==    by 0x134DBCA0: std::vector<int, std::allocator<int> >::push_back(int const&) (stl_vector.h:923)
==10808==    by 0x13523510: wave::GroundSegmentation<pcl::PointXYZI>::sectorINSAC(int) (ground_segmentation.hpp:314)
==10808==    by 0x1352085C: wave::GroundSegmentation<pcl::PointXYZI>::applyFilter(pcl::PointCloud<pcl::PointXYZI>&) (ground_segmentation.hpp:366)
==10808==    by 0x134E1B2B: pcl::Filter<pcl::PointXYZI>::filter(pcl::PointCloud<pcl::PointXYZI>&) (filter.h:151)
==10808==    by 0x134C6FCF: occupancy::OccupancyNodelet::segmentGround() (occupancy_nodelet.cpp:540)
==10808==    by 0x134C48DB: occupancy::OccupancyNodelet::lidarCallBack(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) (occupancy_nodelet.cpp:270)
==10808==    by 0x1350BEF8: boost::_mfi::mf1<void, occupancy::OccupancyNodelet, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::operator()(occupancy::OccupancyNodelet*, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) const (mem_fn_template.hpp:165)
==10808==    by 0x135075DA: void boost::_bi::list2<boost::_bi::value<occupancy::OccupancyNodelet*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, occupancy::OccupancyNodelet, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >, boost::_bi::list1<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, occupancy::OccupancyNodelet, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >&, boost::_bi::list1<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>&, int) (bind.hpp:313)
==10808==    by 0x13502EBE: void boost::_bi::bind_t<void, boost::_mfi::mf1<void, occupancy::OccupancyNodelet, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >, boost::_bi::list2<boost::_bi::value<occupancy::OccupancyNodelet*>, boost::arg<1> > >::operator()<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>&&) (bind.hpp:905)
==10808==    by 0x134FD3C0: boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, occupancy::OccupancyNodelet, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >, boost::_bi::list2<boost::_bi::value<occupancy::OccupancyNodelet*>, boost::arg<1> > >, void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) (function_template.hpp:159)
```

### PR DESCRIPTION
**Pull request by mpitropov**
Closes #285 

#### Pre-Merge Checklist:
- [ ] Code is documented in doxygen format
- [x] Code has automated tests
- [X] Zero compiler warnings
- [X] Formatted with `clang-format`

### CODE REVIEW

File: wave_matching/include/wave/matching/impl/ground_segmentation.hpp [hunk 1]
```diff
@@ -47,8 +47,7 @@ void GroundSegmentation<PointT>::genPolarBinGrid() {
 
         if (sqrt(px * px + py * py + pz * pz) < this->params.rmax) {
             double ph = (atan2(py, px)) * (180 / M_PI);  // in degrees
-            if (ph < 0)
-                ph = 360.0 + ph;
+            ph = wave::wrapTo360(ph);
```
Comment (leokoppel) [inline wave_matching/include/wave/matching/impl/ground_segmentation.hpp]: This is already in `wave` namespace right?

Comment (mpitropov) [reply wave_matching/include/wave/matching/impl/ground_segmentation.hpp]: yep, I'll take it out
